import "./globals.css";
import { Providers } from "./providers";

// export const metadata = {
//   title: "My Information",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children, params: { locale } }) {
//   return (
//     <html lang={locale}>
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export default async function LocaleLayout({ children, params: { locale } }) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
