import ClientLayout from "./clientLayout";
import "./globals.css";

export const metadata = {
  title: "My Information",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <ClientLayout children={children} />;
}
